name: orbit
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orbit
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    container_name: db.orbit.internal
    ports:
      - "3306:3306"