spring:
  application:
    name: orbit
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://${DATABASE_ADDRESS:localhost}:3306/orbit?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&maxReconnects=10"
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

---
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}

---
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
---
openai:
  api-key: ${OPENAI_API_KEY}