spring:
  application:
    name: orbit
  profiles:
    active: test
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

---
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}

---
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
---
openai:
  api-key: ${OPENAI_API_KEY}

---
cloud:
  aws:
    s3:
      bucket: orbit-dev-env
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false