spring:
  application:
    name: orbit
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: multilingual-e5-large
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
---
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}

---
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
---
cloud:
  aws:
    s3:
      bucket: orbit-dev-env
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false
---
fcm:
  fcm-url: ${FCM_URL}
---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}